# NUMPY PRACTICE

In [4]:
import numpy as np


In [14]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep2270588361616
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


In [17]:
#test whether none of the elements of a given array are zero
a=np.array([[1,2,3],[7,8,9]])
print(np.all(a))

True


In [20]:
#getting help with an function
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [22]:
#test if each element is finite
a = np.array([56, 8, 0, np.inf])
print("Original array")
print(a)

# Checking the given array 'a' element-wise for finiteness and printing the result
print("Test a given array element-wise for finiteness :")
print(np.isfinite(a)) 

Original array
[56.  8.  0. inf]
Test a given array element-wise for finiteness :
[ True  True  True False]


In [2]:
y=np.array([[1,2,3],[3,3,4]])
print(y)

[[1 2 3]
 [3 3 4]]


In [5]:
y=np.array([[[1,2,3],[3,3,4],[9,0,9]]])
print(y)

[[[1 2 3]
  [3 3 4]
  [9 0 9]]]


In [6]:
print(y.ndim)

3


In [8]:
ar=np.array([1,2,3],ndmin=10)
print(ar)

[[[[[[[[[[1 2 3]]]]]]]]]]


In [29]:
a1 = np.arange(28)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [30]:
a2 = np.reshape (a1, (7,4), 'F') #f means values are generated column wise
print(a2)

[[ 0  7 14 21]
 [ 1  8 15 22]
 [ 2  9 16 23]
 [ 3 10 17 24]
 [ 4 11 18 25]
 [ 5 12 19 26]
 [ 6 13 20 27]]


In [33]:
a3 = np.reshape (a1, (7,4), 'C') #c means values generated row wise
print(a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]


In [35]:
a4 = np.reshape (a1, (2,2,7), 'F')
print(a4)

[[[ 0  4  8 12 16 20 24]
  [ 2  6 10 14 18 22 26]]

 [[ 1  5  9 13 17 21 25]
  [ 3  7 11 15 19 23 27]]]


In [37]:
a2 = np.reshape (a1, (2,2,7), 'c')
print(a2)

[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]]

 [[14 15 16 17 18 19 20]
  [21 22 23 24 25 26 27]]]


In [38]:
arr1 = np.arange(20)
print (arr1)
arr_slice = slice(1,10,2)
print(arr_slice,'\n')
print(arr1[arr_slice])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
slice(1, 10, 2) 

[1 3 5 7 9]


In [39]:
print(arr1.itemsize) #size of each element in bytes
#For int32 array, each element requires 4 bytes (32 bits) of memory.
#For float64 array, each element requires 8 bytes (64 bits) of memory.
print(arr1.size) #no. of elements

4
20


In [40]:
#empty array
arr5 = np.empty([3,2], dtype = float) #used to create array without initializing it's memory
print (arr5)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [12]:
ar=np.zeros((4,2,1))
print(ar)

[[[0.]
  [0.]]

 [[0.]
  [0.]]

 [[0.]
  [0.]]

 [[0.]
  [0.]]]


In [13]:
ar=np.zeros((4,2,2))
print(ar)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [11]:
ar=np.zeros((4,2))
print(ar)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [15]:
b=np.ones(4)
b

array([1., 1., 1., 1.])

In [19]:
c=np.empty(4)
c

array([1., 1., 1., 1.])

In [23]:
# Creating an array of 10 fives by multiplying an array of 10 ones by 5
array = np.ones(10) * 5
array

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [22]:
ar=np.arange(1,11,2,dtype=float)
ar

array([1., 3., 5., 7., 9.])

In [23]:
d=np.eye(4,5,k=1)
d

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
d=np.eye(4,5,k=0)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [26]:
ar=np.linspace(1,5,11)
ar

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [27]:
var=np.random.rand(8)
var

array([0.82859887, 0.93817072, 0.10044582, 0.59438382, 0.76159782,
       0.37114464, 0.15388491, 0.99747908])

In [29]:
var=np.random.randn(8)
var

array([ 0.09730614, -2.15587346, -1.37856785, -0.44084805, -1.68932495,
        0.52894483,  0.2306176 , -2.04234587])

In [30]:
var=np.random.randint(8,90,20)
var

array([65, 28, 77, 22, 45, 65, 15, 54, 81, 47, 84, 29, 19, 50, 39, 64, 42,
       46, 59, 36])

In [37]:

var=np.array(var,dtype=float)
print(var.dtype)

float64
float64


In [42]:
new=var.astype(int)
new

array([65, 28, 77, 22, 45, 65, 15, 54, 81, 47, 84, 29, 19, 50, 39, 64, 42,
       46, 59, 36])

In [43]:
np.argmin(var)

6

In [44]:
np.argmax(var)

10

In [45]:
var


array([65., 28., 77., 22., 45., 65., 15., 54., 81., 47., 84., 29., 19.,
       50., 39., 64., 42., 46., 59., 36.])

In [46]:
d=np.array([[2,1,3],[9,5,6]])
print(np.min(d,axis=0))
print(np.min(d,axis=1))

[2 1 3]
[1 5]


In [47]:
np.cumsum(var)

array([ 65.,  93., 170., 192., 237., 302., 317., 371., 452., 499., 583.,
       612., 631., 681., 720., 784., 826., 872., 931., 967.])

In [48]:
d.shape

(2, 3)

In [51]:
x=d.reshape(-1)
x

array([2, 1, 3, 9, 5, 6])

In [56]:
k=np.array([[1,2,3],[1,2,3]])
for i in k:
    for j in i:
        print(j)
    print("\n")

1
2
3


1
2
3




In [63]:
for i in np.nditer(k, flags=['buffered'], op_dtypes=['S']):
    print(i)

b'1'
b'2'
b'3'
b'1'
b'2'
b'3'


In [66]:
for i,d in np.ndenumerate(k):
    print(i,d)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 1
(1, 1) 2
(1, 2) 3


In [68]:
cop=var.copy()
cop


array([65., 28., 77., 22., 45., 65., 15., 54., 81., 47., 84., 29., 19.,
       50., 39., 64., 42., 46., 59., 36.])

In [70]:
vi=var.view()
vi

array([65., 28., 77., 22., 45., 65., 15., 54., 81., 47., 84., 29., 19.,
       50., 39., 64., 42., 46., 59., 36.])

In [76]:

var=np.append(5,var)
var

array([ 5., 65., 28., 77., 22., 45., 65., 15., 54., 81., 47., 84., 29.,
       19., 50., 39., 64., 42., 46., 59., 36.])

In [81]:
ar=np.concatenate((x,var))
ar

array([ 2.,  1.,  3.,  9.,  5.,  6.,  5., 65., 28., 77., 22., 45., 65.,
       15., 54., 81., 47., 84., 29., 19., 50., 39., 64., 42., 46., 59.,
       36.])

In [82]:
vr=np.array([[1,2],[3,4]])
vr1=np.array([[9,8],[4,1]])
ar_New=np.concatenate((vr,vr1),axis=0)
ar_New

array([[1, 2],
       [3, 4],
       [9, 8],
       [4, 1]])

In [83]:
vr=np.array([[1,2],[3,4]])
vr1=np.array([[9,8],[4,1]])
ar_New1=np.concatenate((vr,vr1),axis=1)
ar_New1

array([[1, 2, 9, 8],
       [3, 4, 4, 1]])

In [85]:
new_stack=np.dstack((vr,vr1))
new_stack

array([[[1, 9],
        [2, 8]],

       [[3, 4],
        [4, 1]]])

In [86]:
np.array_split(var,3)

[array([ 5., 65., 28., 77., 22., 45., 65.]),
 array([15., 54., 81., 47., 84., 29., 19.]),
 array([50., 39., 64., 42., 46., 59., 36.])]

In [91]:
a=np.array([1,2,3,3,42,2,3,2,2])
x=np.where(a==2)
print(x)
l=np.searchsorted(a,5)
print(l)
print(np.sort(a))

(array([1, 5, 7, 8], dtype=int64),)
4
[ 1  2  2  2  2  3  3  3 42]


In [92]:
var1=np.array(['a','s','d','f'])
f=[True,False,False,True]
newa=var1[f]
newa

array(['a', 'f'], dtype='<U1')

In [98]:
np.random.shuffle(var1)
var1

array(['d', 'a', 'f', 's'], dtype='<U1')

In [109]:
x=np.unique(a)
y=np.resize(x,(2,2))
y

array([[ 1,  2],
       [ 3, 42]])

In [112]:
np.delete(var1,1)

array(['d', 'f', 's'], dtype='<U1')

In [41]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [43]:
x = np.array([1, 2, 3])
y = np.array([4, 5])
X, Y = np.meshgrid(x, y) #It returns two 2D arrays, one for the x-coordinates and one for the y-coordinates, representing the coordinates of all points in the grid.
print(X)
print(Y)

[[1 2 3]
 [1 2 3]]
[[4 4 4]
 [5 5 5]]


In [46]:
arr = np.array([1, 5, 10, 15, 20])

# Clip the array to be between 5 and 15
clipped_arr = np.clip(arr, 5, 15)

print(clipped_arr)

[ 5  5 10 15 15]


In [6]:
m=np.matrix([[1,2,3,4,],[1,2,3,4]])
m

matrix([[1, 2, 3, 4],
        [1, 2, 3, 4]])

In [7]:
type(m)

numpy.matrix

In [9]:
m1=np.matrix([[1,2],[2,3]])
m2=np.matrix([[1,2],[2,3]])
print(m1*m2)
print(m1.dot(m2))

[[ 5  8]
 [ 8 13]]
[[ 5  8]
 [ 8 13]]


In [10]:
var = np.matrix([[1,2,3],[1,2,3]])
print(np.transpose(var))
print(var.T)

[[1 1]
 [2 2]
 [3 3]]
[[1 1]
 [2 2]
 [3 3]]


In [11]:
var = np.matrix([[1,2,],[2,2]])
print(np.linalg.inv(var)) 

[[-1.   1. ]
 [ 1.  -0.5]]


In [12]:
var = np.matrix([[1,2,],[3,5]])
print(np.linalg.matrix_power(var,3))

[[ 43  74]
 [111 191]]


In [13]:
var = np.matrix([[1,2],[3,5]])
print(np.linalg.det(var))

-1.0000000000000004
